version: '3'
services:
  container-1:
    # Using a Dockerfile is optional, but included for completeness.
    build: 
      context: ./node-express-api-1/.devcontainer
      dockerfile: Dockerfile
      # [Optional] You can use build args to set options. e.g. 'VARIANT' below affects the image in the Dockerfile
      # args: 
      #   VARIANT: buster
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
      - container-2
    # ...

  container-2:
    # Using a Dockerfile is optional, but included for completeness.
    build: 
      context: ./node-express-api-2/.devcontainer
      dockerfile: Dockerfile
      # [Optional] You can use build args to set options. e.g. 'VARIANT' below affects the image in the Dockerfile
      # args: 
      #   VARIANT: buster
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    # ...